"""Functions to aid in DAG graphical analysis."""

from pathlib import Path

import networkx as nx


def _modularise_rulegraph(
    rulegraph: nx.DiGraph, module_prefixes: list[str]
) -> nx.DiGraph:
    """Wrap module rules into a single rule with a special marker.

    Prefixes are necessary to distinguish models from regular rules.
    """
    labels = nx.get_node_attributes(rulegraph, "label")
    # Ensure labels are clean strings
    labels = {key: value.replace('"', "") for key, value in labels.items()}

    modulegraph = rulegraph.copy()
    for prefix in module_prefixes:
        module_node_attrs = dict(label=prefix, color="0 0 0", style="diagonals")
        modulegraph.add_node(prefix, **module_node_attrs)

        module_nodes = set(
            key for key, value in labels.items() if value.startswith(prefix)
        )
        for edge in rulegraph.edges:
            if not set(edge) - module_nodes:
                # edge is completely within the module
                modulegraph.remove_edge(*edge)
            elif edge[0] in module_nodes and edge[1] not in module_nodes:
                # edge is a module output
                modulegraph.add_edge(prefix, edge[1])
            elif edge[0] not in module_nodes and edge[1] in module_nodes:
                # edge is a module input
                modulegraph.add_edge(edge[0], prefix)

        modulegraph.remove_nodes_from(module_nodes)

    return modulegraph


def transform_rulegraph_to_modulegraph(
    rulegraph_path: Path | str, output_path: Path | str, module_prefixes: list[str]
):
    """Create a PNG file with a simplified DAG with a single rule per module.

    Args:
        rulegraph_path (Path | str): path to .dot generated by `snakemake --rulegraph`.
        output_path (Path | str): location to save the resulting PNG.
        module_prefixes (list[str]): list of module prefixes to simplify.

    Raises:
        ValueError: input was not a .dot file.
    """
    if not str(rulegraph_path).endswith(".dot"):
        raise ValueError("Only .dot files can be processed.")

    rulegraph = nx.DiGraph(nx.nx_pydot.read_dot(rulegraph_path))
    modulegraph = _modularise_rulegraph(rulegraph, module_prefixes)
    dot_graph = nx.drawing.nx_pydot.to_pydot(modulegraph)
    dot_graph.write_png(output_path)
